#!/usr/bin/env python3
# ═══════════════════════════════════════════════════════════════════
#  Mox HUB — Engine Embedder
#  Run this ONCE after building the engine to embed the binary
#  into engine_payload.py so the HUB can install without internet.
#
#  Usage:
#    python HUB/embed_engine.py
#  Or automatically from: HUB/build_and_embed.bat
# ═══════════════════════════════════════════════════════════════════

import os
import sys
import base64
import struct
import hashlib
import zipfile
import tempfile
from datetime import datetime

HUB_DIR      = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(HUB_DIR)

# ─── Candidate build output directories (in priority order) ────────
BUILD_DIRS = [
    os.path.join(PROJECT_ROOT, "build"),
    os.path.join(PROJECT_ROOT, "Engine", "build"),
    os.path.join(PROJECT_ROOT, "build_mingw"),
    os.path.join(PROJECT_ROOT, "dist", "windows"),
]

# ─── Files to embed (relative to build dir) ────────────────────────
# MoxEngine.exe / Nova2D.exe  + SDL2.dll are mandatory.
# scripts/ folder is optional but bundled if present.
EXE_NAMES   = ["MoxEngine.exe", "Nova2D.exe"]
DLL_NAMES   = ["SDL2.dll", "SDL2_image.dll", "SDL2_mixer.dll", "SDL2_ttf.dll"]
EXTRA_DIRS  = ["scripts", "assets"]

OUTPUT_FILE  = os.path.join(HUB_DIR, "engine_payload.py")
VERSION_TAG  = "Mox Engine1"
MAX_EMBED_MB = 80   # safety cap — warn if bundle exceeds this

# ───────────────────────────────────────────────────────────────────
def find_build_dir():
    for d in BUILD_DIRS:
        for name in EXE_NAMES:
            if os.path.exists(os.path.join(d, name)):
                return d, name
    return None, None


def collect_files(build_dir, exe_name):
    """Returns list of (relative_path, absolute_path) tuples."""
    files = []

    # 1. Main executable
    exe_path = os.path.join(build_dir, exe_name)
    files.append(("MoxEngine.exe", exe_path))

    # 2. DLLs in build dir
    for dll in DLL_NAMES:
        p = os.path.join(build_dir, dll)
        if os.path.exists(p):
            files.append((dll, p))

    # 3. Extra dirs (scripts, assets)
    for dname in EXTRA_DIRS:
        dpath = os.path.join(build_dir, dname)
        if os.path.isdir(dpath):
            for root, _, fnames in os.walk(dpath):
                for fname in fnames:
                    abs_path = os.path.join(root, fname)
                    rel_path = os.path.relpath(abs_path, build_dir).replace("\\", "/")
                    files.append((rel_path, abs_path))

    return files


def pack_to_zip(file_list):
    """Pack all files into an in-memory zip, return bytes."""
    import io
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as zf:
        for rel_path, abs_path in file_list:
            zf.write(abs_path, rel_path)
    return buf.getvalue()


def write_payload(zip_bytes, exe_name, file_list):
    b64 = base64.b64encode(zip_bytes).decode("ascii")
    sha = hashlib.sha256(zip_bytes).hexdigest()
    size_mb = len(zip_bytes) / (1024 * 1024)

    manifest = [rel for rel, _ in file_list]

    lines = [
        "# AUTO-GENERATED by HUB/embed_engine.py — DO NOT EDIT MANUALLY",
        f"# Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"# Engine:    {VERSION_TAG}",
        f"# Bundle:    {size_mb:.2f} MB (compressed)",
        f"# Files:     {', '.join(manifest)}",
        f"# SHA-256:   {sha}",
        "",
        "ENGINE_VERSION  = " + repr(VERSION_TAG),
        "ENGINE_EXE_NAME = 'MoxEngine.exe'",
        f"ENGINE_SHA256   = {repr(sha)}",
        f"ENGINE_MANIFEST = {repr(manifest)}",
        "",
        "# Base64-encoded zip archive of the engine bundle",
        "ENGINE_PAYLOAD_B64 = (",
    ]

    # Split into 100-char lines for readability
    chunk = 100
    for i in range(0, len(b64), chunk):
        lines.append(f"    {repr(b64[i:i+chunk])}")

    lines += [")", ""]

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def main():
    print("=" * 56)
    print("  Mox HUB — Engine Embedder")
    print("=" * 56)

    build_dir, exe_name = find_build_dir()

    if not build_dir:
        print()
        print("  ❌  No engine binary found!")
        print()
        print("  Searched in:")
        for d in BUILD_DIRS:
            print(f"    • {d}")
        print()
        print("  Build the engine first:")
        print("    build_incremental.bat   (MinGW)")
        print("  or:")
        print("    cmake --build build_mingw --config Release")
        print()
        sys.exit(1)

    print(f"\n  ✓  Found binary: {os.path.join(build_dir, exe_name)}")
    file_list = collect_files(build_dir, exe_name)

    print(f"\n  Bundling {len(file_list)} file(s):")
    total_raw = 0
    for rel, abs_p in file_list:
        sz = os.path.getsize(abs_p)
        total_raw += sz
        print(f"    + {rel:40s}  ({sz/1024:.0f} KB)")

    print(f"\n  Compressing... ({total_raw/1024/1024:.2f} MB raw)")
    zip_bytes = pack_to_zip(file_list)
    size_mb   = len(zip_bytes) / (1024 * 1024)
    print(f"  Compressed to {size_mb:.2f} MB")

    if size_mb > MAX_EMBED_MB:
        print(f"\n  ⚠  Bundle is large ({size_mb:.1f} MB). Consider stripping debug symbols.")

    print(f"\n  Writing {OUTPUT_FILE} ...")
    write_payload(zip_bytes, exe_name, file_list)
    print("  ✅  engine_payload.py generated successfully!")
    print()
    print("  The HUB will now offer 'Install Mox Engine' which")
    print("  extracts the bundled binary instantly — no internet needed.")
    print()


if __name__ == "__main__":
    main()
